# prettier configuration
arrowParens: always
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 70
proseWrap: always
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
