#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
PATH="/Users/samyang/.nvm/versions/node/v14.17.3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin"
npx lint-staged
